config/routes.rb
TodoApp::Application.routes.draw do
  root :to => "home#index"
  resources :projects do
    resources :items, :only => [:index]
  end

  resources :items, :except => [:index] do
    collection do
      get "search"
      put "update_batch"
    end
    
  end
  resources :users
  resources :teams do
    resources :projects, :only => [:new]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :project
  attr_accessible :completed, :description, :title, :project_id
  validates :title, :description ,:presence=> true

  # REV: nice fattening of the model :)
  def self.search(query)
    query.delete "title" if query["title"] == ""
    query["completed"] = query["completed"] == "false" ? false : true if query["completed"]
    
    @results = Item
    if query.include?(:title)
      @results = @results.where("title LIKE '%#{query[:title]}%'")
    end
    if query.include?(:completed)
      @results = @results.where("completed =?", query[:completed])
    end
    @results = @results.all
    # @movies = Movie
    # if query.include?(:name)
    #   @movies = @movies.where(:name => query[:name])
    # end
    # if query.include?(:completed)
    #   @movies = @movies.where(:complted => true)
    # end

    # @movies = @movies.all
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # REV: blank lines should go between attr_accessible and 
  # relationships, also before validates lines
  attr_accessible :description, :title, :team_id
  has_many :items
  belongs_to :team
  # REV: you should also validate title length
  # and any string value because of descrepencies 
  # between sql storage of TEXT and Rails' definition
  # of string(255)
  validates :title, :description, :presence=> true
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name

  has_many :projects
  has_many :team_memberships
  has_many :users, :through => :team_memberships

  validates :name, :presence => true

  def to_s
    name
  end
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :team_ids
  has_many :team_memberships
  has_many :teams, :through => :team_memberships
  has_many :projects, :through => :teams
  has_many :items, :through => :projects

  validates :name, :team_ids, :presence=> true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.where(:project_id => params[:project_id])
    @item = Item.new
    @item.project_id = params[:project_id]
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])
    render :show
  end

  def create
    @item = Item.create!(params[:item])
    redirect_to project_items_url(@item.project)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to project_url(@item.project)
  end

  def search
    query = params[:query]
    query = Item.search(query)
    @items = query
  end

  def update_batch
    items = params[:item]
    items.each do |k,query|
      item = Item.find(k.to_i)
      item.update_attributes(query)
    end
    project = Item.find(items.keys[0]).project
    redirect_to project_url(project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    @team = @project.team
  end

  def new
    @project = Project.new
    @project.team_id = params[:team_id]
  end

  def create
    @project = Project.create!(params[:project])
    redirect_to projects_url
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
    @team = Team.new
  end

  def show
    @team = Team.find(params[:id])
    @projects = @team.projects
    @users = @team.users
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    if @team.save
      redirect_to teams_url
    else
      flash.now["notice"] = @team.errors.full_messages
      render :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @teams = @user.teams
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    if @user.save
      redirect_to user_url(@user)
    else
      # REV: nice use of flash, you could also use it to
      # indicate a successful save with flash["success"]
      # i think
      flash.now["notice"] = @user.errors.full_messages
      render :edit
    end
  end

  def create
    @user = User.new
    @user.attributes = params[:user]
    if @user.save
      redirect_to users_url
    else
      flash.now["notice"] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def show_detail_info(item)
    "desc: #{item.description} | completed: #{item.completed}"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_item_search.html.erb
<br>
<!-- REV: cool query form :) -->
<%= form_tag('/items/search', :method => :get) %>
<%= label_tag "item_search", "Item Search:" %>
<%= text_field_tag "query[title]", nil,:id => "item_search"%>
<br>
<div class="radio-toolbar">
<%= radio_button_tag "query[completed]", true, false, :id => "radio_complete" %>
<%= label_tag "radio_complete", "Complete" %>
<%= radio_button_tag "query[completed]", false, false, :id => "radio_incomplete" %>
<%= label_tag "radio_incomplete", "Incomplete" %>
</div>
<br>
<%= submit_tag "Search", :class => 'btn' %>

app/views/home/index.html.erb
<br>
<div class="container-fluid" >
<%= link_to "Teams", teams_url %>
|
<%= link_to "Users", users_url %>
|
<%= link_to "Projects", projects_url %>
<br>
<%= render :partial => "item_search" %>
</div>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description ,:rows => 1%>

  <%= f.collection_select :project_id, Project.all, :id, :title %>

  <%= f.submit %>
<% end %>

app/views/items/_item_detail.html.erb
<%= link_to item_detail.title, item_url(item_detail) %>
| Desc:
<%= truncate item_detail.description, :length => 10 %>
| Completed:
<%= item_detail.completed %>
<br>

app/views/items/index.html.erb
<h1> Items </h1>
<%= render :partial => "form" %>
<br>
<br>
<!-- REV: nice job pulling these into partials.
remember the shortcut: if your variable passed will
be named the same as your partial title, you can just pass: :partial => "item_detail", :object => item_detail -->
<% @items.each do |item_detail| %>
  <%= render :partial => "item_detail", :locals => {:item_detail=> item_detail}%>

<% end %>
<br>
<br>

app/views/items/new.html.erb
<h1> Create New Item </h1>
<%= render :partial => 'form' %>

app/views/items/search.html.erb
<h1> Items Search Results </h1>

<br>
<% @items.each do |item_detail| %>
<%= render :partial => "item_detail", :locals => {:item_detail=> item_detail}%>

<% end %>
<br>
<br>

app/views/items/show.html.erb
<h1> <%= @item.title %></h1>

<h3> Details </h3>

<ul>
<li> Project: <%=link_to @item.project.title, project_url(@item.project)%> </li>
<li> Description: <%= @item.description %> </li>
<li> Complete: <%= @item.completed %> </li>


</ul>

<%= form_for @item do |f| %>
  <%= f.hidden_field :completed, :value => true %>
  <%= f.submit "Complete" %>
<% end %>

<%= form_for @item do |f| %>
  <%= f.hidden_field :completed, :value => false %>
  <%= f.submit "Incomplete" %>
<% end %>

<%= button_to "Delete", item_url(@item), :method => :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash["notice"] %>
<% flash["notice"].each do |notice| %>
<%= notice %>
<% end %>
<% end %>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<!-- for organization, maybe put some blank lines between
field sets -->
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.collection_select :team_id, Team.all, :id, :name  %>
  <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h1> Projects </h1>

<% @projects.each do |project| %>
  <li><%= link_to project.title, project_url(project) %></li>

<% end %>
<br>

<%= render :partial => "form" %>
<br>
or
<br>
<br>
<%= link_to "Create New Project" , new_project_url%>

app/views/projects/new.html.erb
<h1> Create New Project </h1>

<%= render :partial=>'form' %>

app/views/projects/show.html.erb
<h1> <%= @project.title %></h1>

<h3> Team: <%= link_to @team.name, team_url(@team)%> </h3>
<h3> Desc: <%= @project.description %> </h3>


<h3> Items: </h3>
<%=link_to "View all Items in Detail", project_items_url(@project) %>  
<br>
<br>
<% unless @project.items.empty? %>

<%= form_tag('/items/update_batch', :method=>:put) %>
  <% @project.items.each do |item| %>
    <li>
      <%= link_to item.title, item_url(item) %>
      <%= hidden_field_tag "item[#{item.id}][completed]", false %>
      <%= check_box_tag "item[#{item.id}][completed]", true, item.completed%>
    </li>
  <% end %>
  <br>
  <%= submit_tag "Update Items" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :name, "Name:" %>
<%= f.text_field :name %>
<br>
Teams:
<% Team.all.each do |team| %>
<%= check_box_tag(
  "user[team_ids][]",
  team.id,
  @user.teams.include?(team),
  :id => "team_id_#{team.id}"
  ) %>
<%= label_tag "team_id_#{team.id}", team.name%>

<%end%>
<% hidden_field_tag "user[team_ids][]", "" %>
<br>
<%= f.submit %>
<%end%>

app/views/users/edit.html.erb
<h1> Edit New User </h1>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1> Users </h1>

<% @users.each do |user| %>
  <li><%= link_to user.name, user_url(user) %></li>
<% end %>
<br>

<%= link_to "Create New User" , new_user_url %>

app/views/users/new.html.erb
<h1> Create New User </h1>

<%= render :partial=>'form' %>

app/views/users/show.html.erb
<h1> <%= @user.name %></h1>


<h4> Teams: </h4>

<% unless @teams.empty? %>
<% @teams.each do |team| %>
 <li><%= link_to team.name, team_url(team) %></li>
<% end %>
<% end %>
<h4> Items: </h4>
<% @user.items.each do |item| %>
<li><%= link_to item.title, item_url(item) %></li>
 <% end %>
<br>
<br>
<%= link_to "Edit User", edit_user_url(@user) %> |
<%= link_to "Delete User", user_url(@user), :method => :delete %>